name: "Has Changes"
description: "Check if a git repository has uncommitted changes"
branding:
  icon: "info"
  color: "yellow"
inputs:
  status-args:
    description: "Arguments to the `git status` command."
    required: false
    default: ""
  pathspec:
    description: "Pattern used to limit paths in the `git status` command."
    required: false
    default: ""
  working-directory:
    description: "The directory where the Git repository is located, used to support checking out to custom locations or checking out multiple repos in parallel"
    required: false
    default: ""
outputs:
  changed:
    description: "Whether or not there are uncommitted changes in the pathspec"
runs:
  using: "docker"
  image: "Dockerfile"
  args: 
    - ${{ inputs.status-args }}
    - ${{ inputs.pathspec }}
    - ${{ inputs.working-directory }}
